" ---------------------------------------------------------------------------
" Bootstrap vim-plug
" ---------------------------------------------------------------------------
let s:plug_path = has('nvim') ? stdpath('data') . '/site/autoload/plug.vim'
      \ : '~/.vim/autoload/plug.vim'
if empty(glob(s:plug_path))
  silent execute '!curl -fLo ' . s:plug_path . ' --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

" Sensible starting defaults so this file can focus on preferences
Plug 'tpope/vim-sensible'

" Editing
Plug 'tpope/vim-surround'        " cs"' , ds" , ysiw' etc.
Plug 'tpope/vim-commentary'      " gcc / gc to (un)comment
Plug 'tpope/vim-repeat'          " let . repeat plugin maps above
Plug 'jiangmiao/auto-pairs'      " auto-close (), [], "", etc.

" Git
Plug 'tpope/vim-fugitive'        " :G status/blame/diff
Plug 'airblade/vim-gitgutter'    " +/-/~ signs in the gutter

" Fuzzy finding (project already has fzf installed, just add the vim glue)
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'

" Status line + colorscheme
Plug 'itchyny/lightline.vim'
Plug 'morhetz/gruvbox'

call plug#end()

" ---------------------------------------------------------------------------
" General
" ---------------------------------------------------------------------------
set nocompatible
filetype plugin indent on
syntax on

set encoding=utf-8
set hidden                 " keep buffers around when switching without saving
set updatetime=300
set timeoutlen=500
set backspace=indent,eol,start
set mouse=a                 " mouse support in the terminal
set clipboard=unnamedplus   " share the system clipboard by default

" Persistent undo across sessions
set undofile
set undodir=~/.vim/undodir
if !isdirectory(&undodir)
  call mkdir(&undodir, 'p')
endif

" Keep swap/backup files out of the way instead of littering cwd
set backupdir=~/.vim/backup//
set directory=~/.vim/swap//
if !isdirectory(&backupdir) | call mkdir(&backupdir, 'p') | endif
if !isdirectory(&directory) | call mkdir(&directory, 'p') | endif

" ---------------------------------------------------------------------------
" UI
" ---------------------------------------------------------------------------
set number relativenumber
set cursorline
set signcolumn=yes
set colorcolumn=100
set scrolloff=8
set showmatch
set wrap
set linebreak
set noshowmode              " lightline already shows the mode
set laststatus=2

set background=dark
silent! colorscheme gruvbox

let g:lightline = { 'colorscheme': 'gruvbox' }

" ---------------------------------------------------------------------------
" Indentation
" ---------------------------------------------------------------------------
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set autoindent
set smartindent

" ---------------------------------------------------------------------------
" Search
" ---------------------------------------------------------------------------
set ignorecase
set smartcase
set incsearch
set hlsearch

" ---------------------------------------------------------------------------
" Splits
" ---------------------------------------------------------------------------
set splitright
set splitbelow

" ---------------------------------------------------------------------------
" Leader + mappings
" ---------------------------------------------------------------------------
let mapleader = ' '
let maplocalleader = ' '

" Clear search highlight
nnoremap <silent> <leader><cr> :nohlsearch<cr>

" Quick save / quit
nnoremap <leader>w :w<cr>
nnoremap <leader>q :q<cr>

" Move between splits with ctrl+hjkl
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Keep visual selection after indenting
vnoremap < <gv
vnoremap > >gv

" Move selected lines up/down
vnoremap J :m '>+1<cr>gv=gv
vnoremap K :m '<-2<cr>gv=gv

" fzf.vim
nnoremap <leader>ff :Files<cr>
nnoremap <leader>fg :GFiles<cr>
nnoremap <leader>fb :Buffers<cr>
nnoremap <leader>fw :Rg<cr>

" fugitive
nnoremap <leader>gs :G<cr>
nnoremap <leader>gb :G blame<cr>
